
  
name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.1.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - name: Build and test with Rake
        env:
          RAILS_ENV: test           
        run: |        
          gem install bundler          
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rake
          COVERAGE=true bundle exec rspec
      - name: Rubocop Check
        run: |
          bundle exec rubocop
